function [X,fval,exitflag,output]=Inve(k,a,b,Tc,R,A,B,C,D,E,PARA0)

options = optimset('Display','on','MaxFunEvals',10000,'MaxIter',10000,'TolX',1e-2,'TolFun',1e-2);
%'OutputFcn',@functn,
    
    
    [X,fval,exitflag,output]=fminsearch(@(PARA0) objfun(k,a,b,Tc,R,A,B,C,D,E,PARA0),PARA0,options);

        
%     function stop=functn(PARA0,optimValues)
%         stop=false;
%         if abs(optimValues.fval)<1e-05 || optimValues.fval==0
%           stop=true;
%         end
%     end



    function F=objfun(k,a,b,Tc,R,A,B,C,D,E,PARA0)
F=((PARA0(1).*((-((R./(PARA0(2)-b))-((a*(-(k/Tc)*(exp(k*(1-(PARA0(1)./Tc))))))./...
        ((PARA0(2).^2)+(2*b*PARA0(2))-(b^2)))))./...
        (((2*a*(exp(k*(1-(PARA0(1)./Tc))))*(PARA0(2)+b))./...
        (((PARA0(2).^2)+(2*b*PARA0(2))-(b^2))^2)))-((R*PARA0(1))./...
        ((PARA0(2)-b).^2))))-PARA0(2))./...
        ((((A+(B*PARA0(1))+(C*(PARA0(1).^2))+(D*(PARA0(1).^3))+(E*(PARA0(1).^4)))-R)+(PARA0(1)*...
     ((a*(((k/Tc)^2)*(exp(k*(1-(PARA0(1)./Tc))))))/(2*sqrt(2)*b))*(log((PARA0(2)+...
     ((1+sqrt(2))*b))/(PARA0(2)+((1-sqrt(2))*b))))))-((PARA0(1)*...
     (((R/(PARA0(2)-b))-((a*(-(k/Tc)*(exp(k*(1-(PARA0(1)./Tc))))))/...
     ((PARA0(2)^2)+(2*b*PARA0(2))-(b^2)))).^2))./....
     ((((2*a*(exp(k*(1-(PARA0(1)./Tc))))*(PARA0(2)+b))./(((PARA0(2).^2)+(2*b*PARA0(2))-(b^2)).^2)))...
     -((R*PARA0(1))./((PARA0(2)-b).^2)))));
    end

end

